export const NewData = [
  {
    title: "Rajasthan CM Ashok Gehlot in Delhi amid political crisis in state",
    link: "https://www.sentinelassam.com/national-news/rajasthan-cm-ashok-gehlot-in-delhi-amid-political-crisis-in-state-621768",
    keywords: ["National News,More"],
    creator: ["Sentinel Digital Desk"],
    video_url: null,
    description:
      "Gehlot will address 10 public meetings and will also hold a press conference in Rajkot and visit Sardar Vallabhbhai Patel’s birth place and native village in Karamsad.",
    content:
      "JAIPUR: Amid the ongoing political crisis, Rajasthan Chief Minister Ashok Gehlot on Friday left for Delhi. He is supposed to reach Delhi in a special plane at 4 p.m. where he will meet senior Congress leaders. Gehlot will make a night halt in Delhi.Next day, on November 5, he will be on an election tour of Gujarat for three days from November 5 to November 7. Gehlot will address 10 public meetings and will also hold a press conference in Rajkot. He will also visit Sardar Vallabhbhai Patel's birth place and native village in Karamsad. Gehlot, who is the senior observer of the Congress party in the Gujarat assembly elections, will be accompanied by Raghu Sharma, election in-charge for the state. In all public meetings, Gehlot will appeal to the general public to vote in support of the Congress candidates in the assembly elections. Meanwhile, political uncertainty prevails in Rajasthan as former deputy chief minister Sachin Pilot on Wednesday had asked Congress high command to take disciplinary action against three Gehlot loyalists, two ministers and one RTDC president, who convened a parallel meeting when an official meeting was already called by Congress high command on September 25. Pilot also termed it as an interesting development after Prime Minister Narendra Modi praised Gehlot, saying that Modi praised Ghulam Nabi the same way as he did praise Gehlot. We know what happened thereafter, Pilot quipped. (IANS)Also Read: Assam: Badruddin Ajmal Re- Elected as AIUDF PresidentAlso Watch: ",
    pubDate: "2022-11-05 11:24:54",
    image_url:
      "https://assets.sentinelassam.com/h-upload/2022/11/05/500x300_409597-rajasthan-cm-gehlot-pti-1103730-1650877809-1106280-1651632682-1112849-1653624754.jpg",
    source_id: "sentinel",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title: "‘You are Pakistan’s hero’, says Imran Khan as he meets his saviour",
    link: "https://www.thehindu.com/news/international/you-are-pakistans-hero-says-imran-khan-as-he-meets-his-saviour/article66099836.ece",
    keywords: null,
    creator: ["\n        PTI  \n    "],
    video_url: null,
    description:
      "Jemima Goldsmith, the ex-wife of Imran Khan, expressed relief as her former husband is stable after the assassination attempt",
    content: null,
    pubDate: "2022-11-05 11:24:03",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title:
      "Ensure hat-trick of Congress win: CLP leader Agnihotri’s call to voters in Haroli",
    link: "https://www.thehindu.com/news/national/other-states/ensure-hat-trick-of-congress-win-clp-leader-agnihotris-call-to-voters-in-haroli/article66099791.ece",
    keywords: null,
    creator: ["\n        PTI  \n    "],
    video_url: null,
    description:
      "Haroli in Himachal Pradesh’s Una district is a key constituency for the Congress",
    content: null,
    pubDate: "2022-11-05 11:14:24",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title:
      "CCPA levies ₹1 lakh fine on Cloudtail for selling pressure cookers on Amazon in violation of BIS standards",
    link: "https://www.thehindu.com/business/ccpa-levies-1-lakh-fine-on-cloudtail-for-selling-pressure-cookers-on-amazon-in-violation-of-bis-standards/article66099771.ece",
    keywords: null,
    creator: ["\n        PTI  \n    "],
    video_url: null,
    description:
      "The CCPA initiated suo-moto action against e-commerce platforms for sale of domestic pressure cookers in violation to compulsory standard",
    content: null,
    pubDate: "2022-11-05 11:13:45",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title:
      "Minister inspects waterlogged areas in Madurai, directs officials to repair roads",
    link: "https://www.thehindu.com/news/cities/Madurai/minister-inspects-waterlogged-areas-in-madurai-directs-officials-to-repair-roads/article66099665.ece",
    keywords: null,
    creator: ["\n        The Hindu Bureau  \n    "],
    video_url: null,
    description:
      "Minister for Registration P. Moorthy inspected several areas in the city along with local officials; he said temporary road work would be taken up immediately, and permanent roads would be laid after the monsoon",
    content: null,
    pubDate: "2022-11-05 11:13:38",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title:
      "Tamil producer claims Atlee plagiarised Vijayakanth’s film for Shah Rukh Khan’s Jawan, files complaint",
    link: "https://indianexpress.com/article/entertainment/tamil/tamil-producer-claims-atlee-plagiarised-vijayakanth-film-for-shah-rukh-khans-jawan-more-deets-here-8251408/",
    keywords: ["Entertainment", "Tamil"],
    creator: null,
    video_url: null,
    description: null,
    content: null,
    pubDate: "2022-11-05 11:11:58",
    image_url: null,
    source_id: "indianexpress",
    country: ["india"],
    category: ["entertainment"],
    language: "english",
  },
  {
    title:
      "State Assembly polls | Congress always ignored Himachal because of low representation in Lok Sabha: PM Modi",
    link: "https://www.thehindu.com/news/national/other-states/state-assembly-polls-congress-always-ignored-himachal-because-of-low-representation-in-lok-sabha-pm-modi/article66099760.ece",
    keywords: null,
    creator: ["\n        PTI  \n    "],
    video_url: null,
    description:
      "The hill state has a history of not electing the same party to power for two consecutive terms. The BJP is in power in the state and is leaving no stone unturned to retain it",
    content: null,
    pubDate: "2022-11-05 11:10:01",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title:
      "“Anti-reservation” comments by IIT-B Prof, National Commission for Scheduled Tribe issues notice",
    link: "https://www.edexlive.com/news/2022/nov/05/anti-reservation-comments-by-iit-b-prof-national-commission-for-scheduled-tribe-issues-notice-32004.html",
    keywords: null,
    creator: ["Edex Live"],
    video_url: null,
    description:
      "Students had earlier demanded that the SC/ST Cell and the administration take immediate action against the professor and remove her from the position she holds",
    content:
      "The National Commission for Scheduled Tribes has taken cognisance of a complaint filed against the Head Counsellor of the Student Wellness Centre at the Indian Institute of Technology Bombay regarding comments made by her which were “anti-reservation” in nature, according to students. The notice that has been issued to K Sanjay Murthy, Secretary, Ministry of Education, on November 1, stated, “Whereas a petition/complaint has been received…from Ambedkar Periyar Phule Study Circle, IIT Bombay dated June 16, 2022...and the commission has decided to investigate/inquire into the matter.” It has directed the aforementioned authority to submit the facts and information on the action taken on these allegations within 15 days of receipt of the notice. The study circle stated in an email sent to the officials of the institute that the Head Counsellor of SWC, Hima Anaredy, passed casteist remarks about reservation and questioned the merit of those students who avail reservation. “The students do not feel safe or comfortable going to talk about their mental health issues to such a person who is sharing their casteist views against a constitutional provision for representation of underrepresented communities,” the email stated. The group of students also attached the post by the concerned professor in a tweet “where she is openly calling for ending of reservation”.",
    pubDate: "2022-11-05 11:07:00",
    image_url:
      "https://images.edexlive.com/uploads/user/imagelibrary/2021/12/30/w600X390/iit_bombay.jpeg",
    source_id: "edexlive",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
  {
    title: "Skin changes in monkeypox in the genital area",
    link: "https://www.techexplorist.com/skin-changes-monkeypox-genital-area/54706/",
    keywords: ["Health", "Monkeypox"],
    creator: ["Amit Malewar"],
    video_url: null,
    description:
      "Monkeypox can take a variety of clinical courses. Continue reading Skin changes in monkeypox in the genital area on Tech Explorist.",
    content: null,
    pubDate: "2022-11-05 11:06:57",
    image_url: null,
    source_id: "techexplorist",
    country: ["india", "singapore"],
    category: ["health"],
    language: "english",
  },
  {
    title:
      "Citizens must show equal respect to Jana Gana Mana, Vande Mataram: Centre to Delhi High Court",
    link: "https://www.thehindu.com/news/national/citizens-must-show-equal-respect-to-jana-gana-mana-vande-mataram-centre-to-delhi-high-court/article66099732.ece",
    keywords: null,
    creator: ["\n        PTI  \n    "],
    video_url: null,
    description:
      "The submission was made by the Ministry of Home Affairs on an affidavit filed in response to a public interest litigation by lawyer Ashwini Kumar Upadhyay to ensure that the song 'Vande Mataram' is as honoured and given equal status as the national anthem.",
    content: null,
    pubDate: "2022-11-05 11:05:43",
    image_url: null,
    source_id: "thehindu",
    country: ["india"],
    category: ["top"],
    language: "english",
  },
];
